export const familyEventsData = [
  {
    Date: "Every Tuesday",
    Time: "5:15 PM",
    Borough: "Brooklyn",
    "Event ": "Free Chess Workshop",
    Org: "Brooklyn Public Library",
    Location: "93 Saint Edwards Street Brooklyn, NY 11205",
    Ages: null,
    Link: "https://www.eventbrite.com/e/free-chess-workshop-for-kids-and-teens-tickets-759813471547?aff=ebdssbdestsearch",
  },
  {
    Date: "12/17/2023",
    Time: "10:30 AM",
    Borough: "Bronx",
    "Event ": "Family Program",
    Org: "Lehman College Art Gallery",
    Location: "250 Bedford Park Boulevard West Bronx, NY 10468",
    Ages: "All Ages",
    Link: "https://www.eventbrite.com/e/free-inclusive-family-program-children-of-all-ages-welcome-tickets-736675013797?aff=ebdssbdestsearch",
  },
  {
    Date: "12/2/23",
    Time: "2:00 PM",
    Borough: "Brooklyn",
    "Event ": "Sinterklaas - Saint Nicholas Day Celebration",
    Org: "Fidler-Wyckoff House Park",
    Location: "5816 Clarendon Road Brooklyn",
    Ages: "All Ages",
    Link: "https://www.eventbrite.com/e/sinterklaas-saint-nicholas-day-tickets-758008221997?aff=oddtdtcreator",
  },
  {
    Date: "12/3/23",
    Time: "12:00 PM",
    Borough: "Bronx",
    "Event ": "Creative Art Family Edition",
    Org: "Williamsbridge Oval Recreation Center",
    Location: "3225 Reservoir Oval East, Bronx",
    Ages: "All Ages",
    Link: null,
  },
  {
    Date: "12/4/23",
    Time: "11:00 AM",
    Borough: "Queens",
    "Event ": "Tiny Tots",
    Org: "Detective Keith L. Williams Field House",
    Location: "106-16 173 Street, Queens",
    Ages: "18 months - 3 Years",
    Link: null,
  },
  {
    Date: "12/8/23",
    Time: "4:30 PM",
    Borough: "Bronx",
    "Event ": "Recreation Without Limits: Creative Art Workshop",
    Org: "Williamsbridge Oval Recreation Center",
    Location: "3225 Reservoir Oval East, Bronx",
    Ages: "All Ages",
    Link: null,
  },
  {
    Date: "12/9/23",
    Time: "11:00 AM",
    Borough: "Manhattan",
    "Event ": "Holiday Wreath Making",
    Org: "Pelham Fritz Recreation Center ",
    Location: "18 Mount Morris Park West, New York, NY 10027, Manhattan",
    Ages: "All Ages",
    Link: null,
  },
];
