export const holidayEventsData = [
  {
    Date: "12/22/23",
    Time: "7:00 PM",
    Borough: "Brooklyn",
    "Event ": "Winter Wonder",
    Org: "Kingdom Fire & Destiny",
    Location: "1102 Clarkson Avenue Brooklyn, NY 11212",
    Ages: "ALL AGES",
    Link: "https://www.eventbrite.com/e/winter-wonder-ignite-the-gifts-toy-giveaway-tickets-769979458287?aff=ebdssbdestsearch",
  },
  {
    Date: "12/17/23",
    Time: "2:30 PM",
    Borough: "Brooklyn",
    "Event ": "Toy Drive & Give Away",
    Org: "Jesus Outreach Tabernacle",
    Location: "572 Rockaway Avenue #2nd floor Brooklyn, NY 11207",
    Ages: "ALL AGES",
    Link: "https://www.eventbrite.com/e/christmas-toys-giveaway-tickets-770028565167?aff=ebdssbdestsearch",
  },
  {
    Date: "12/22/23",
    Time: "5:00 PM",
    Borough: "Bronx",
    "Event ": "Toy Ganza",
    Org: "ELOHIM",
    Location: "991 Longwood Avenue The Bronx, NY 10459",
    Ages: "ALL AGES",
    Link: "https://www.eventbrite.com/e/holiday-toyganza-toy-givaway-tickets-767741695077?aff=ebdssbdestsearch",
  },
  {
    Date: "12/17/23",
    Time: "3:00 PM",
    Borough: "Brooklyn",
    "Event ": "4th Annual Christmas Extravaganza",
    Org: "The Courtney's Corner Community Foundation",
    Location: "74 Pennsylvania Avenue Brooklyn, NY 11207",
    Ages: "ALL AGES",
    Link: "https://www.eventbrite.com/e/4th-annual-christmas-extravaganza-tickets-765050896827?aff=ebdssbdestsearch",
  },
  {
    Date: "12/6/23",
    Time: "6:00 PM",
    Borough: "Uniondale",
    "Event ": "Feliz Navidad Holiday Celebration & Concert 2023",
    Org: "Mitchel Athletic Complex",
    Location: "1 Charles Lindbergh Boulevard Uniondale, NY 11553",
    Ages: "ALL AGES",
    Link: "https://www.eventbrite.com/e/feliz-navidad-holiday-celebration-concert-2023-tickets-750034883527?aff=ebdssbdestsearch",
  },
];
